#ifndef __STYLEHTML_H
#define __STYLEHTML_H

/* Auto-generated from style.html - do not edit manually */

/*
 * Each original line becomes a separate element in the array below.
 * Simple inline comments and block comments are removed.
 * Trailing whitespace is trimmed; empty lines are skipped.
 */

static const char *styleHTML[] = {
    "<!-- Inline CSS for styling the page -->",
    "<style>",
    "    html {",
    "        font-family: courier;",
    "        font-size: 24px;",
    "        display: inline-block;",
    "        margin: 0 auto;",
    "        text-align: center;",
    "    }",
    "    body {",
    "        background-color: white;",
    "        color: black;",
    "        font-family: courier;",
    "        padding: 20px;",
    "    }",
    "    .button {",
    "        background-color: red;",
    "        border: none;",
    "        color: white;",
    "        padding: 16px 40px;",
    "        text-decoration: none;",
    "        font-size: 30px;",
    "        margin: 2px;",
    "        cursor: pointer;",
    "    }",
    "    .button2 { background-color: black; }",
    "    .button3 { background-color: grey; }",
    "    .button4 { background-color: green; }",
    "    .center {",
    "        margin-left: auto;",
    "        margin-right: auto;",
    "    }",
    "    .warning-container {",
    "        padding: 38px 40px;",
    "        padding-bottom: 0;",
    "        box-sizing: border-box;",
    "        text-align: center;",
    "        background-color: white;",
    "        border: 1px solid #D4D4D4;",
    "        height: 484px;",
    "        width: 484px;",
    "        margin: 0 auto;",
    "        margin-top: 10%;",
    "        box-shadow: 0px 0px 41px -8px rgba(237,234,237,1);",
    "    }",
    "    .header {",
    "        margin: 26px 0 0 0;",
    "        color: #363B3E;",
    "        font-size: 45px;",
    "        font-weight: 500;",
    "    }",
    "    .top-content {",
    "        margin: 0;",
    "        color: #9BA0A3;",
    "        margin-bottom: 35px;",
    "    }",
    "    .bottom-content {",
    "        display: inline-block;",
    "        height: 120px;",
    "        line-height: 120px;",
    "    }",
    "    .bottom-content > span {",
    "        display: inline-block;",
    "        vertical-align: middle;",
    "        line-height: normal;",
    "    }",
    "    table {",
    "        margin: 0 auto;",
    "        white-space: nowrap;",
    "        border-collapse: collapse;",
    "    }",
    "    footer {",
    "        text-align: center;",
    "        font-size: 16px;",
    "        padding: 3px;",
    "        background-color: MediumSeaGreen;",
    "        color: white;",
    "    }",
    "    #status {",
    "        color: lightgray;",
    "        margin-bottom: 10px;",
    "        font-size: 16px;",
    "        text-align: left;",
    "    }",
    "    #terminal {",
    "        height: 400px;",
    "        overflow-y: auto;",
    "        border: 2px solid MediumSeaGreen;",
    "        padding: 10px;",
    "        background-color: #000;",
    "        color: white;",
    "        margin-bottom: 10px;",
    "        white-space: pre-wrap;",
    "        text-align: left;",
    "        font-size: 16px;",
    "    }",
    "    #input {",
    "        width: 100%;",
    "        background-color: #1e1e1e;",
    "        color: #ffffff;",
    "        border: 2px solid MediumSeaGreen;;",
    "        font-family: monospace;",
    "        font-size: 16px;",
    "        outline: none;",
    "    }",
    "    .error { color: red; }",
    "    .warning { color: orange; }",
    "</style>",
};

#define STYLEHTML_COUNT (sizeof(styleHTML) / sizeof((styleHTML)[0]))

#endif /* __STYLEHTML_H */
